In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use("ggplot")

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [0]:
path="drive/My Drive/1001_project_total/Data/"
df=pd.read_csv(path+"20170101_sknn.csv")
articles=df["id"].unique()
d={}
for i in range(len(articles)):
    article=articles[i]
    d[article]=i
df["articleId"]=df["id"].map(d)

# Category

In [0]:
path="drive/My Drive/1001_project_total/wrong/category/"

## ItemKNN

In [0]:
itemknn=pd.read_csv(path+"itemknn_wrong.txt",sep=",",names=["sessionNo","rank"])
itemknn["sessionNo"]=itemknn["sessionNo"].apply(lambda x:int(x[1:]))
itemknn["rank"]=itemknn["rank"].apply(lambda x:x[:-1])
selected=pd.merge(df,itemknn,on="sessionNo",how="inner")

In [92]:
a=selected.groupby("deviceType").size()
b=df.groupby("deviceType").size()
device=pd.concat((a,b),axis=1)
device["prop"]=device[0]/device[1]
print("The type of device with ascending number of wrong recommendation: ")
device.sort_values("prop")

The type of device with ascending number of wrong recommendation:

                0       1      prop
deviceType
Mobile      16516  128496  0.128533
Tablet       8723   63317  0.137767
Desktop      8925   61177  0.145888

In [144]:
import math
a=selected.groupby("category_num").size()
b=df.groupby("category_num").size()
device=pd.concat((a,b),axis=1)
device["prop"]=device[0]/device[1]
print("The type of device with most number of wrong recommendation: ")
device.sort_values("prop",inplace=True)
k=device[["prop"]].index.values
for i in range(len(k)):
  if i<=10:
    print("The category number:")
    print(k[i])
    print("The category name:")
    print(selected[selected["category_num"]==k[i]]["category1"].unique())

The type of device with most number of wrong recommendation:
The category number:
5
The category name:
['100sport|sjakk']
The category number:
36
The category name:
['nyheter|nordtrondelag']
The category number:
4
The category name:
['100sport|mesterskap']
The category number:
2
The category name:
['100sport|fotball']
The category number:
47
The category name:
['pluss|magasin']
The category number:
33
The category name:
['nyheter|innenriks']
The category number:
11
The category name:
['bolig|boligguiden']
The category number:
19
The category name:
['kultur|musikk']
The category number:
23
The category name:
['kultur|vin']
The category number:
38
The category name:
['nyheter|oppdraget']
The category number:
44
The category name:
['nyheter|utenriks']

## SKNN

In [0]:
sknn=pd.read_csv(path+"sknn_wrong.txt",sep=",",names=["sessionNo","rank"])
sknn["sessionNo"]=sknn["sessionNo"].apply(lambda x:int(x[1:]))
sknn["rank"]=sknn["rank"].apply(lambda x:x[:-1])
selected=pd.merge(df,sknn,on="sessionNo",how="inner")

In [148]:
import math
a=selected.groupby("category_num").size()
b=df.groupby("category_num").size()
device=pd.concat((a,b),axis=1)
device["prop"]=device[0]/device[1]
print("The type of device with most number of wrong recommendation: ")
device.sort_values("prop",inplace=True)
k=device[["prop"]].index.values
for i in range(len(k)):
  if i<=10:
    print("The category number:")
    print(k[i])
    print("The category name:")
    print(selected[selected["category_num"]==k[i]]["category1"].unique())

The type of device with most number of wrong recommendation:
The category number:
5
The category name:
['100sport|sjakk']
The category number:
2
The category name:
['100sport|fotball']
The category number:
33
The category name:
['nyheter|innenriks']
The category number:
42
The category name:
['nyheter|sortrondelag']
The category number:
36
The category name:
['nyheter|nordtrondelag']
The category number:
4
The category name:
['100sport|mesterskap']
The category number:
7
The category name:
['100sport|vintersport']
The category number:
43
The category name:
['nyheter|trondheim']
The category number:
39
The category name:
['nyheter|politikk']
The category number:
47
The category name:
['pluss|magasin']
The category number:
37
The category name:
['nyheter|okonomi']

# Article

In [0]:
path="drive/My Drive/1001_project_total/wrong/article/"

## ItemKNN

In [0]:
itemknn=pd.read_csv(path+"itemknn_wrong.txt",sep=",",names=["sessionNo","rank"])
itemknn["sessionNo"]=itemknn["sessionNo"].apply(lambda x:int(x[1:]))
itemknn["rank"]=itemknn["rank"].apply(lambda x:x[:-1])
selected=pd.merge(df,itemknn,on="sessionNo",how="inner")

In [18]:
a=selected.groupby("deviceType").size()
b=df.groupby("deviceType").size()
device=pd.concat((a,b),axis=1)
device["prop"]=device[0]/device[1]
print("The type of device with ascending number of wrong recommendation: ")
device.sort_values("prop")

The type of device with ascending number of wrong recommendation:

               0       1      prop
deviceType
Mobile      9067  128496  0.070563
Tablet      7757   63317  0.122511
Desktop     7516   61177  0.122857

In [24]:
selected.groupby("articleId").size()

articleId
0       2730
1        613
2          2
3       1550
4        566
        ...
1097       2
1122       6
1174       2
1279       1
1291       1
Length: 176, dtype: int64

In [26]:
import math
a=selected.groupby("articleId").size()
b=df.groupby("articleId").size()
device=pd.concat((a,b),axis=1)
device["prop"]=device[0]/device[1]
device.sort_values("prop",inplace=True,ascending=False)
print(device)
k=device[["prop"]].index.values[:20]
for i in range(len(k)):
  if i<=10:
    print("The article number:")
    print(k[i])
    print("The article name:")
    print(selected[selected["articleId"]==k[i]]["a"].unique())

             0  1  prop
articleId
665        5.0  1   5.0
919        4.0  1   4.0
1122       6.0  2   3.0
719        3.0  1   3.0
1037       3.0  1   3.0
...        ... ..   ...
1286       NaN  1   NaN
1287       NaN  1   NaN
1288       NaN  2   NaN
1289       NaN  1   NaN
1290       NaN  1   NaN

[1292 rows x 3 columns]
The article number:
665
The article name:
[]
The article number:
919
The article name:
[]
The article number:
1122
The article name:
[]
The article number:
719
The article name:
[]
The article number:
1037
The article name:
[]
The article number:
1036
The article name:
[]
The article number:
342
The article name:
[]
The article number:
808
The article name:
[]
The article number:
1174
The article name:
[]
The article number:
747
The article name:
[]
The article number:
1000
The article name:
[]